security:
            
    encoders:
        Projet\UserBundle\Entity\Compte:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: Projet\UserBundle\Entity\Compte
                property: email
    firewalls:
        dev:
            pattern: ^/static
            security: false

        prod:
            pattern: ^/static
            security: false 

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                success_handler: authentication_handler
                failure_handler: authentication_handler
                require_previous_session: false
            logout:
                path:   /logout
                target: /    