# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    
    authentication_handler:
        class: Projet\UserBundle\Security\AuthenticationHandler
        public: false
        arguments:
            router : '@router'
            session: '@session'