<?php

namespace Projet\UserBundle\Repository;

/**
 * AgentmarketingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentmarketingRepository extends \Doctrine\ORM\EntityRepository
{
}
