<?php

namespace Projet\UserBundle\Repository;

/**
 * AgentTechniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentTechniqueRepository extends \Doctrine\ORM\EntityRepository
{
}
