<?php


namespace Projet\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends EntityRepository{
   
    public function findbyet($etat){ 
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.etat = :etat')
          ->setParameter('etat', $etat) ;

        return $qb->getQuery()->getResult();
    }
}
