<?php

namespace Projet\UserBundle\Repository;

/**
 * ExpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDispo($b)
{ 
        $qb = $this->createQueryBuilder('a');

        $qb
          ->where('a.disponible = :b')
          ->setParameter('b', $b)
        ;

        return $qb
          ->getQuery()
          ->getResult()
        ;
}


}
