<?php

namespace Projet\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertRepository extends EntityRepository{
   
    
    public function findDispo($b){ 
        $qb = $this->createQueryBuilder('a');

        $qb ->where('a.disponible = :b')->setParameter('b', $b);

        return $qb->getQuery()->getResult();
    }


}
