<?php

namespace Projet\UserBundle\Repository;

/**
 * NotificationOuvrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationOuvrierRepository extends \Doctrine\ORM\EntityRepository
{
}
