<?php

namespace Projet\UserBundle\Repository;

/**
 * NotificationExpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationExpertRepository extends \Doctrine\ORM\EntityRepository
{
}
