<?php

use Doctrine\ORM\EntityRepository;

namespace Projet\UserBundle\Repository;

/**
 * SatisfactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SatisfactionRepository extends EntityRepository
{
}
