<?php

namespace Projet\UserBundle\Repository;

/**
 * SatisfactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SatisfactionRepository extends \Doctrine\ORM\EntityRepository
{
}
